version: '3.1'

services:

  postgres:
    image: postgres:9.4.4
    environment:
      - POSTGRES_USER=playbasic
      - POSTGRES_PASSWORD=playbasic
      - POSTGRES_DB=play_basic
    ports:
      - "5432:5432"

  schema:
      image: claycephas/flyway
      command: -url=jdbc:postgresql://${DOCKER_IP}:5432/play_basic -schemas=public -user=playbasic -password=playbasic -locations=filesystem:/dbscripts migrate
      volumes:
        - .:/dbscripts
      depends_on:
        - postgres

  play-basic:
    image: play-basic:0.0.1-2-g64d2b82-SNAPSHOT
    depends_on:
      - schema
      - postgres
    environment:
      - PostgresUrl=jdbc:postgresql://${DOCKER_IP}:5432/play_basic
    hostname: play-basic
    ports:
      - 9000:9000