version: '3'

services:

  db:
    image: postgres:9.4.4
    environment:
      POSTGRES_USER: playbasic
      POSTGRES_PASSWORD: playbasic
      POSTGRES_DB: playbasic
    ports:
      - 5431:5432

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2180:2181

  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "internal-infos-events_v1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9091:9092

  schema:
      image: gsengun/flyway-postgres:1.4
      restart: always
      command: db 5432 playbasic playbasic playbasic public
      volumes:
        - ./flyway/migration/postgres:/flyway/sql
      depends_on:
        - db

  playbasic:
      # not supported by sbt docker compose
#      build: ./target/docker/stage
    image: markymark1/play-basic:latest
    depends_on:
      - schema
      - db
      - kafka
      - zookeeper
    environment:
      PostgresUrl: jdbc:postgresql://db:5432/playbasic
      KafkaBootstrapServers: kafka:9092
    ports:
      - 9000:9000