version: '3.1'

services:

  postgres:
    image: postgres:9.4.4
    environment:
      - POSTGRES_USER=playbasic
      - POSTGRES_PASSWORD=playbasic
      - POSTGRES_DB=play_basic
    ports:
      - "5432:5432"

#  Note....the schema execution is a little unpredictable as the db needs to be up and awaiting connections before, currently
# this is not possible in docker compose yet :(
  schema:
      image: claycephas/flyway
      command: -url=jdbc:postgresql://${DOCKER_IP}:5432/play_basic -schemas=public -user=playbasic -password=playbasic -locations=filesystem:/dbscripts migrate
      volumes:
        - .:/dbscripts
      depends_on:
        - postgres

  play-basic:
    #  build: ./target/docker/stage // not supported by sbt docker compose
    image: play-basic:0.0.2-3-gd38df3f-SNAPSHOT
    depends_on:
      - schema
      - postgres
    environment:
      - PostgresUrl=jdbc:postgresql://${DOCKER_IP}:5432/play_basic
    hostname: play-basic
    ports:
      - 9000:9000