//
// This is generated code. Do not edit this file.
//
package api.client.play_basic.models

import api.client.play_basic.tags._



case class Info(
  id: Option[ids.InfoId] = None,
  name: String,
  data: play.api.libs.json.JsObject,
  meta: Seq[String]
)
         

case class Problem(
  title: String,
  status: Int,
  detail: String,
  trackingId: Option[ids.TrackingId] = None
)
         

         
